# Modpack Checker Configuration
# This file contains both server and client configuration

# Server Configuration
[server]
# Enable or disable modpack version checking
enable = true

# Expected modpack version that clients must have
expected_version = "1.2.3"

# Kick messages for different scenarios
[server.messages]
# Message shown when client doesn't have the mod installed
no_mod = "❌ Please install the ModpackChecker mod: https://triibu.tech/minecraft"

# Message shown when client has wrong version (use {version} as placeholder)
wrong_version = "❌ Please install modpack version {version}: https://triibu.tech/minecraft"

# Message shown when there's a server configuration error
server_error = "❌ Server configuration error. Please contact an administrator."

# Client Configuration
[client]
# Current modpack version - this should match the server's expected version
version = "1.2.3" 